base:
  - base.yaml

tag: video_demo

data:
  type: SingleBayerDictSet
  camera: Sony
  load_npy: true
  num_workers: 10
  pin_memory: true
  process:
    max_clip: 1.0
    min_clip: null
  test:
    batch_size: 2
    ratio: 50
